# Generated by Django 3.2.9 on 2021-11-13 09:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prifile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
